inf_description = "cyber security machine learning algorithm compilation database data structure data analysis big data AI no SQL database "
bio_description = "Pharmaco-Toxicologie Toxicologie Fondamentale Biomembranes et Communications Cellulaires Physiopathologie des grandes fonctions"
st_description = "Energies et environnement Etat de l'art du génie électrique Mécanique rationnelle Mécanique des fluides Ondes et vibrations"
math_description = "Probabilités avancées Statistique paramétrique Structure Machine Analyse numérique matricielle algebre "
sm_description = "Ethique et déontologie Structure et spectroscopie de molécules diatomiques Chimie organique polyfonctionnelle"
sport_description = "collective sport football handballs basktballs Individual sport swimming athletics"
