# Generated by Django 4.1.7 on 2023-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etud',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('password1', models.CharField(max_length=10)),
            ],
        ),
    ]
