# Generated by Django 4.1.7 on 2023-04-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
