# Generated by Django 4.1.7 on 2023-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_etud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etud',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
