# Generated by Django 4.1.7 on 2023-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_etud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='matr',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
