# Generated by Django 4.1.7 on 2023-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_remove_etud_id_remove_etud_matr_etud_matrucul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etud',
            name='matrucul',
        ),
        migrations.AddField(
            model_name='etud',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
