# Generated by Django 4.1.7 on 2023-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_remove_etud_matrucul_etud_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etud',
            name='matruculation_etud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
