# Generated by Django 4.1.7 on 2023-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_etud_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etud',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
