# Generated by Django 4.1.7 on 2023-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_biologiesc_mathc_sioncematierec_sioncetechnologiesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifourmatiquec',
            name='Modul',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
