# Generated by Django 4.1.7 on 2023-04-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_ifourmatiquec_modul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep', models.CharField(max_length=70)),
                ('Modul', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=70)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BiologiesC',
        ),
        migrations.DeleteModel(
            name='IfourmatiqueC',
        ),
        migrations.DeleteModel(
            name='MathC',
        ),
        migrations.DeleteModel(
            name='SionceMatiereC',
        ),
        migrations.DeleteModel(
            name='SionceTechnologiesC',
        ),
        migrations.DeleteModel(
            name='SportC',
        ),
    ]
