# Generated by Django 4.1.7 on 2023-04-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cours_delete_biologiesc_delete_ifourmatiquec_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Etud_Cours',
        ),
    ]
