# Generated by Django 4.1.7 on 2023-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_cours_etud_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etud_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Depp', models.CharField(max_length=70)),
                ('Modull', models.CharField(max_length=70)),
                ('descriptionn', models.TextField()),
                ('titlee', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
