# Generated by Django 4.1.7 on 2023-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etud_questions',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
