# Generated by Django 4.1.7 on 2023-05-07 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0010_alter_etud_questions_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Ann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_Ann', models.CharField(max_length=200)),
                ('Description_Ann', models.CharField(max_length=200)),
                ('title_Ann', models.CharField(max_length=100)),
                ('Link_Ann', models.CharField(max_length=500)),
                ('added_Ann', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
